name: release

on:
  push:
    tags-ignore:
      - "v1"
      - "v2"
      - "v3"
      - "v4"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      is_tag: ${{ steps.check.outputs.is_tag }}

    steps:
      - name: Check if it's a tagged release
        id: check
        run: |
          REF=${{ github.ref }}
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/${REF##*/}"
          StatusCode=$(curl -o /dev/null -I -L -s -w "%{http_code}" -X GET -G $URL)
          echo $StatusCode
          if [[ "$StatusCode" == 200 ]]; then
            echo "This is tagged release!"
            echo "IS_TAG=no" >> $GITHUB_OUTPUT
          else
            echo "This is a tag not release!"
            echo "IS_TAG=yes" >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: ubuntu-latest
    container: setsoft/kicad_pybuild:latest
    needs: check
    if: ${{ needs.check.outputs.IS_TAG == 'yes' }}
    outputs:
      DEB_NAME: ${{ steps.mdeb.outputs.DEB_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        id: mdeb
        run: |
          apt-get -y update
          apt-get -y install --no-install-recommends python3-bs4 python3-future python3-lxml python3-requests python3-tqdm wget python3-pip python3-xlsxwriter python3-yaml
          wget https://github.com/INTI-CMNB/KiCost/releases/download/v1.1.5rc1/python3-babel_2.9.0-1_all.deb
          wget https://github.com/INTI-CMNB/KiCost/releases/download/v1.1.5rc5/python3-validators_0.14.2-2_all.deb
          wget https://github.com/set-soft/kicost-digikey-api-v3/releases/download/v0.1.1/kicost-digikey-api-v3_0.1.1-1_all.deb
          wget https://github.com/set-soft/kicost-digikey-api-v4/releases/download/v0.1.3/kicost-digikey-api-v4_0.1.3-1_all.deb
          apt -y install --no-install-recommends ./*.deb
          rm python3-babel*
          cp requirements.txt requirements.txt.ok
          sed -i 's/^wxPython/#wxPython/' requirements.txt
          pip3 install -U .
          cp requirements.txt.ok requirements.txt
          make deb
          mv ../*.deb .
          echo "DEB_NAME="`ls *.deb` >> $GITHUB_OUTPUT
          mkdir output
          mv *.deb output

      - name: Store
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: output

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Retrieve
        uses: actions/download-artifact@v4
        with:
          name: package

      - name: Changelog
        run: |
          tools/history2changelog.py > CHANGELOG.md

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "true"
          PRE_RELEASE: "true"
          CHANGELOG_FILE: "CHANGELOG.md"
          KICOST_RELEASE: "true"
        with:
          args: |
            package/${{needs.build.outputs.DEB_NAME}}

